require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AcquisitionTracksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AcquisitionTrack. As you add validations to AcquisitionTrack, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcquisitionTracksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all acquisition_tracks as @acquisition_tracks" do
      acquisition_track = AcquisitionTrack.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:acquisition_tracks)).to eq([acquisition_track])
    end
  end

  describe "GET #show" do
    it "assigns the requested acquisition_track as @acquisition_track" do
      acquisition_track = AcquisitionTrack.create! valid_attributes
      get :show, {:id => acquisition_track.to_param}, valid_session
      expect(assigns(:acquisition_track)).to eq(acquisition_track)
    end
  end

  describe "GET #new" do
    it "assigns a new acquisition_track as @acquisition_track" do
      get :new, {}, valid_session
      expect(assigns(:acquisition_track)).to be_a_new(AcquisitionTrack)
    end
  end

  describe "GET #edit" do
    it "assigns the requested acquisition_track as @acquisition_track" do
      acquisition_track = AcquisitionTrack.create! valid_attributes
      get :edit, {:id => acquisition_track.to_param}, valid_session
      expect(assigns(:acquisition_track)).to eq(acquisition_track)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AcquisitionTrack" do
        expect {
          post :create, {:acquisition_track => valid_attributes}, valid_session
        }.to change(AcquisitionTrack, :count).by(1)
      end

      it "assigns a newly created acquisition_track as @acquisition_track" do
        post :create, {:acquisition_track => valid_attributes}, valid_session
        expect(assigns(:acquisition_track)).to be_a(AcquisitionTrack)
        expect(assigns(:acquisition_track)).to be_persisted
      end

      it "redirects to the created acquisition_track" do
        post :create, {:acquisition_track => valid_attributes}, valid_session
        expect(response).to redirect_to(AcquisitionTrack.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved acquisition_track as @acquisition_track" do
        post :create, {:acquisition_track => invalid_attributes}, valid_session
        expect(assigns(:acquisition_track)).to be_a_new(AcquisitionTrack)
      end

      it "re-renders the 'new' template" do
        post :create, {:acquisition_track => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested acquisition_track" do
        acquisition_track = AcquisitionTrack.create! valid_attributes
        put :update, {:id => acquisition_track.to_param, :acquisition_track => new_attributes}, valid_session
        acquisition_track.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested acquisition_track as @acquisition_track" do
        acquisition_track = AcquisitionTrack.create! valid_attributes
        put :update, {:id => acquisition_track.to_param, :acquisition_track => valid_attributes}, valid_session
        expect(assigns(:acquisition_track)).to eq(acquisition_track)
      end

      it "redirects to the acquisition_track" do
        acquisition_track = AcquisitionTrack.create! valid_attributes
        put :update, {:id => acquisition_track.to_param, :acquisition_track => valid_attributes}, valid_session
        expect(response).to redirect_to(acquisition_track)
      end
    end

    context "with invalid params" do
      it "assigns the acquisition_track as @acquisition_track" do
        acquisition_track = AcquisitionTrack.create! valid_attributes
        put :update, {:id => acquisition_track.to_param, :acquisition_track => invalid_attributes}, valid_session
        expect(assigns(:acquisition_track)).to eq(acquisition_track)
      end

      it "re-renders the 'edit' template" do
        acquisition_track = AcquisitionTrack.create! valid_attributes
        put :update, {:id => acquisition_track.to_param, :acquisition_track => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested acquisition_track" do
      acquisition_track = AcquisitionTrack.create! valid_attributes
      expect {
        delete :destroy, {:id => acquisition_track.to_param}, valid_session
      }.to change(AcquisitionTrack, :count).by(-1)
    end

    it "redirects to the acquisition_tracks list" do
      acquisition_track = AcquisitionTrack.create! valid_attributes
      delete :destroy, {:id => acquisition_track.to_param}, valid_session
      expect(response).to redirect_to(acquisition_tracks_url)
    end
  end

end
